Set MSRV to 1.59.0 in Cargo.toml (#11)
Currently,
- rpm-rs depends on rsa-der ^0.3.0
- rsa-der 0.3.0 depends on simple_asn1 ^0.6
- simple_asn1 0.6.2 depends on time ^0.3
- time 0.3.14 specifies MSRV 1.59.0

This commit fixes the following error with Rust 1.57.0:
error: package `time v0.3.14` cannot be built because it requires rustc 1.59.0 or newer, while the currently active rustc version is 1.57.0